export const GOOGLE_FONTS: string[] = [
  "Inter",
  "Roboto",
  "Open Sans",
  "Lato",
  "Montserrat",
  "Poppins",
  "Source Sans Pro",
  "Oswald",
  "Raleway",
  "Nunito",
  "Nunito Sans",
  "PT Sans",
  "Merriweather",
  "Ubuntu",
  "Playfair Display",
  "Rubik",
  "Work Sans",
  "DM Sans",
  "Manrope",
  "Space Grotesk",
  "IBM Plex Sans",
  "Barlow",
  "Outfit",
  "Plus Jakarta Sans",
  "Figtree",
  "Geist",
  "Noto Sans",
  "Cabin",
  "Quicksand",
  "Mulish",
  "Josefin Sans",
  "Karla",
  "Libre Franklin",
  "Archivo",
  "Red Hat Display",
  "Sora",
  "Lexend",
  "Albert Sans",
  "Urbanist",
  "Onest",
  "General Sans",
  "Satoshi",
  "Clash Display",
];

export const GOOGLE_FONTS_SET = new Set(GOOGLE_FONTS);

export const FONT_SUBSTITUTIONS: Record<string, string> = {
  "Helvetica": "Inter",
  "Helvetica Neue": "Inter",
  "Arial": "Inter",
  "SuisseIntl-Medium": "Inter",
  "SuisseIntl-Regular": "Inter",
  "Suisse Intl": "Inter",
  "Suisse Int'l": "Inter",
  "Metro Sans": "DM Sans",
  "Metro Sans Bold": "DM Sans",
  "Metro Sans Book": "DM Sans",
  "SF Pro": "Inter",
  "SF Pro Display": "Inter",
  "SF Pro Text": "Inter",
  "Avenir": "Nunito",
  "Avenir Next": "Nunito Sans",
  "Futura": "Poppins",
  "Gill Sans": "Lato",
  "Proxima Nova": "Montserrat",
  "Gotham": "Montserrat",
  "Franklin Gothic": "Source Sans Pro",
  "Segoe UI": "Inter",
  "Trebuchet MS": "Open Sans",
  "Verdana": "Open Sans",
  "Georgia": "Merriweather",
  "Times New Roman": "Playfair Display",
  "Garamond": "Playfair Display",
  "Calibri": "Work Sans",
};

export function isFontAvailable(fontFamily: string): boolean {
  return GOOGLE_FONTS_SET.has(fontFamily.trim());
}
